---
Name: PortfolioCrypto1
Data_Sources:
  - ticker: BTC-USDT
    historical_source: mongoDB
    historical_library: kucoin_historical_1min

Strategies:
  - id: 1
    strategy: Basic_Strategy
    params:
      ticker: BTC-USDT
      entry: 5000
      inicial_action: buy
      quantity : 1

  - id: 2
    strategy: Basic_Strategy
    params:
      ticker: BTC-USDT
      entry: 20000
      inicial_action: buy
      quantity: 1