---
Name: PortfolioCrypto1
Data_Sources:
  - ticker: ETH-USDT
    event_type: bar
    historical_source: mongoDB
    historical_library: kucoin_historical_1min

Strategies:
  - id: 1
    strategy: Basic_Strategy
    params:
      ticker: ETH-USDT
      entry: 2
      inicial_action: buy
      quantity : 1