# docker compose -f docker-compose_financial.yml --env-file ./compose.env up -d
# docker compose -f docker-compose_financial.yml --env-file ./compose.env up -d telegram_financial
version: '3.9'

services:
  data_provider_mt4:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: data_provider_mt4
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/data_realtime_financial.py

  bot_financial_trading:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: bot_financial_trading
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: financial_order
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/portfolio_production.py

  broker_mt4:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: broker_mt4
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: financial_order
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/broker_financial.py

  telegram_financial:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: telegram_financial
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      TRADING_TYPE_DOCKER: financial
    command: python -u ./src/application/bots/telegram_bot.py

  update_mongodb_financial:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: update_mongodb_financial
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/application/bots/financial_trading/update_mongodb_financial.py

networks:
  smartbots_networks:
    ipam:
      config:
        - subnet: 172.20.0.0/24