# docker compose -f docker-compose_betting.yml --env-file ./compose.env up -d  or
# docker-compose -f docker-compose_betting.yml --env-file ./compose.env up -d
# docker compose -f docker-compose_betting.yml --env-file ./compose.env up -d update_mongodb_betting

version: '3.9'

services:
  provider_betting:
    build:
      context: .
      dockerfile:  smartbot-python.dockerfile
    hostname: provider_betting
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/application/bots/betting_trading/data_realtime_betting.py

  bot_betting_trading:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: bot_betting_trading
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/application/bots/betting_trading/portfolio_production_betting.py

  broker_betting:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: broker_betting
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/application/bots/betting_trading/broker_betting.py

  telegram_betting:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname:   telegram_betting
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      TRADING_TYPE_DOCKER: betting
    command: python -u ./src/application/bots/telegram_bot.py

  update_mongodb_betting:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: update_mongodb_betting
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/infrastructure/update_mongodb_betting.py



networks:
  smartbots_networks:
    ipam:
      config:
        - subnet: 172.20.0.0/24