---
Name: PortfolioCrypto1
Data_Sources:
  - ticker: BTC-USDT
    event_type: bar
    historical_source: mongoDB
    historical_library: kucoin_historical_1h

Strategies_Load_From:
  from:

Strategies:
  - id: 1
    strategy: TrendFollowing_ChatGpt
    params:
      ticker: BTC-USDT
      pattern_length: 3
      short_ma_period: 50
      long_ma_period: 200
      quantity: 1
      limit_save_values: 1000
      point_value: 1
      slippage: 0